apiVersion: 1

datasources:
  - name: velomagg-postgres
    uid: velomagg-pg
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: ${PG_USER}
    isDefault: true
    jsonData:
      database: ${PG_DB}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: ${PG_PASSWORD}
