version: 2

models:
  - name: stg_station_status
    columns:
      - name: status_id
        tests: [unique, not_null]
      - name: station_id
        tests: [not_null]
      - name: last_reported
        tests: [not_null]
      - name: num_bikes_available
        tests:
          - not_null
          - accepted_range: {min_value: 0}
      - name: num_docks_available
        tests:
          - not_null
          - accepted_range: {min_value: 0}
      - name: latence_pipeline_s
        description: Doit rester positive (horloges du même hôte Docker).
        tests:
          - accepted_range: {min_value: 0}
  - name: stg_station_information
    columns:
      - name: station_id
        tests: [unique, not_null]
      - name: capacite
        tests:
          - not_null
          - accepted_range: {min_value: 0, max_value: 200}
      - name: lat
        tests:
          - accepted_range: {min_value: 43.4, max_value: 43.8}
      - name: lon
        tests:
          - accepted_range: {min_value: 3.6, max_value: 4.2}
